### ISSUE TITLE
Error in namespaceExport(ns, exports) : undefined exports: score, score<-

### ISSUE THREAD

**Issue by seandavi** [friend1ws/pmsignature#1]
Just following along with the README:

```
> G <- readMPFile(inputFile, numBases = 5)
Error in namespaceExport(ns, exports) : undefined exports: score, score<-
```

**Comment by friend1ws** [comment]
Hi! Thanks for the interest in the pmsignature.
I think this is from the dependency of installed packages..
(just googling "Error in namespaceExport(ns, exports) : undefined exports")

Could you show me the following command?

```
sessionInfo()
```

**Comment by seandavi** [comment]
You are right.  A traceback shows this to be a problem with Biostrings,
most likely:

```
> G <- readMPFile(inputFile, numBases = 5)
Error in namespaceExport(ns, exports) : undefined exports: score, score<-
> traceback()
10: stop(e)
9: value[[3L]](cond)
8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
7: tryCatchList(expr, classes, parentenv, handlers)
6: tryCatch(loadNamespace(name), error = function(e) stop(e))
5: getNamespace(ns)
4: asNamespace(ns)
3: getExportedValue(pkg, name)
2: Biostrings::DNAStringSet
1: readMPFile(inputFile, numBases = 5)
```

I'll figure it out and let you know if there are issues that need to be
dealt with on your end.  Sorry for the noise.

**Comment by friend1ws** [comment]
OK., thanks!!
I welcome any feedbacks and comments.
