### ISSUE TITLE
Can pmsignature support non-human reference genomes? 

### ISSUE THREAD

**Issue by hongenxu** [friend1ws/pmsignature#17]
Hi, 

I am analyzing chicken tumor data, so would you please add support for chicken genome?

Best regards,
Hongen

**Comment by friend1ws** [comment]
Hi, thank you very much for the interest in pmsignature.
Unfortunately, we are now just support only hg19 genome data.
So, I think you need to convert to mutation feature format 
(e.g., https://github.com/friend1ws/pmsignature/blob/devel/inst/extdata/Hoang_MFVF.ind.txt),
and use the readMFVFile function.

But I have been considering to support non-human reference genome,
and try to add the feature sometime in near future.

**Comment by hongenxu** [comment]
Thanks for your help.

**Comment by friend1ws** [comment]
Hi, Now pmsignature can support reference genomes other than hg19 (any genomes that are supported by bioconductor).

For hg18 human genome, 

```
inputFile <- system.file("extdata/Nik_Zainal_2012.mutationPositionFormat.hg18.txt.gz", package="pmsignature")
G <- readMPFile(inputFile, numBases = 5, trDir = TRUE, 
                bs_genome = BSgenome.Hsapiens.UCSC.hg18::BSgenome.Hsapiens.UCSC.hg18,
                txdb_transcript = TxDb.Hsapiens.UCSC.hg18.knownGene::TxDb.Hsapiens.UCSC.hg18.knownGene)
```

For chicken genome, maybe you can try (after installing BSgenome.Ggallus.UCSC.galGal4 and TxDb.Ggallus.UCSC.galGal4.refGene)

```
inputFile <- ${your_own_data}
G <- readMPFile(inputFile, numBases = 5, trDir = TRUE, 
                bs_genome = BSgenome.Ggallus.UCSC.galGal4::BSgenome.Ggallus.UCSC.galGal4,
                txdb_transcript = TxDb.Ggallus.UCSC.galGal4.refGene::TxDb.Ggallus.UCSC.galGal4.refGene
)
```

See also, 
https://www.bioconductor.org/packages/devel/data/annotation/html/TxDb.Ggallus.UCSC.galGal4.refGene.html
https://bioconductor.org/packages/release/data/annotation/html/BSgenome.Ggallus.UCSC.galGal4.html

Hope this becomes help to you.

**Comment by hongenxu** [comment]
really appreciated your help.
