### ISSUE TITLE
Error with new R/Bioconductor updates

### ISSUE THREAD

**Issue by ulah** [friend1ws/pmsignature#18]
Hi,
I have been using pmsignature for a current project quite a lot, but recently (probably after different R/Bioconductor packages updates) readMPFile terminates with the following error:

> mutDataFile <- readMPFile(mutData, numBases = 5, trDir = TRUE, type = "full")
> Error in txdb_bed[gr_txdb@subjectHits] : 
>   no slot of name "subjectHits" for this object of class "SortedByQueryHits"
> In addition: Warning message:
> Using togroup() on a GRangesList object is deprecated. Please use
>   togroup(PartitioningByWidth(...)) instead. 

Any chance this can be fixed in the near future?

Best,
Urs

**Comment by friend1ws** [comment]
Thank you very much for the important feedbacks.
I will try to fix this issue as soon as possible.

**Comment by ulah** [comment]
Finally found the time to confirm that it is working again, thanks a lot!
