### ISSUE TITLE
Can you please elaborate on the Simulated data

### ISSUE THREAD

**Issue by Rashesh7** [friend1ws/pmsignature#23]
Hi,

Can you please elaborate on how you generated the simulated data? For example, if you use K=3 while simulating the data, which 3 signatures are being used? And what are the ranges for alpha and gamma parameters. I am trying to compare a few tools including pmsignature and looking for a simulated data.

**Comment by friend1ws** [comment]
Hi,

Thanks for the interest in our package.
Do you mean the simulation in the paper?
The script used in the paper is at:
https://github.com/friend1ws/pmsignature_paper/blob/master/analysis/simulation/script/runall.sh

Hope this helps for you.

**Comment by Rashesh7** [comment]
Hi, 
Yes, the simulations used in the paper. Thank you for pointing me to the script. 
I had additional question, I am sorry if it is explicit somewhere, but when you mention True signature, are these from a specific file? or are you using the Cosmic Signatures as the base to simulate samples?

**Comment by friend1ws** [comment]
In this simulation, the signatures are generated from scratch by a probabilistic model (products of gamma distribution), and have no relationship with Cosmic Signatures.

**Comment by Rashesh7** [comment]
Oh Ok, then does the tool have the capability of using an input set of signatures to make simulations?

**Comment by friend1ws** [comment]
No. We currently do not support that. For that experiment, you need to generate the set of mutations from e.g. COSMIC signatures with some probabilistic model by yourself.

**Comment by Rashesh7** [comment]
Hi,
Can you please elaborate on the Mutation Feature Vector Format for the   type = "full" format

In the README you have described the format for type = "independent", right?


Basically, I have a file for 21 tumor samples (21 x 96) with number of mutations for each mutation context. Is there are way to directly use that kind of format?
