### ISSUE TITLE
makeSimData function in simulation.R

### ISSUE THREAD

**Issue by zhiiiyang** [friend1ws/pmsignature#26]
Hi, I am developing a new package and borrow the makeSimData function from your package to simulate data. However, I changed a few augments to allow the imbalanced numbers of mutations per sample (you treat them the same across samples) and imported fractions instead of requiring gamma parameters. I am not familiar with borrowing and adapting functions from others' package. How should I acknowledge your work when publishing my package in the future?

**Comment by friend1ws** [comment]
Hi. Thank you very much for the kind notice. I'm happy if you add some description on the partial use of pmsignature package somewhere in your software website. Also, when you publish academic papers, I'm happy if you kindly cite our paper. Thank you very much again!!

**Comment by zhiiiyang** [comment]
I will definitely have a proper citation of your work in any future publications of the package.  For these functions that I borrowed and adapted, I will put a notation there indicating your contribution. Thank you for being generous, kind and helpful. Your work has been truly inspiring.
