### ISSUE TITLE
Inconsistencies in getPMSignature documentation

### ISSUE THREAD

**Issue by funnell** [friend1ws/pmsignature#4]
**Usage**

getPMSignature(mutationFeatureData, K, BG = NULL, numInit = 10, tol = 1e-04, maxIter = 10000)

| Arguments | _ |
| --- | --- |
| mutationFeatureData | the mutation data processed in the function (readMutFile or readRawMutfeatFile) |
| K | the number of mutation signatures |
| numInit | the number of performing calculations with different initial values |
| tol | tolerance for the estimation (when the difference of log-likelihoods become below this value, stop the estimation) |
| maxIter | the maximum number of iteration of estimation |
| isBG | the logical value showing whether a background mutaiton features is included or not |
| BG0 | a background mutaiton feature |

**Comment by friend1ws** [comment]
Thanks! this will be fixed in the next version, which I hope will be available soon.

**Comment by friend1ws** [comment]
fixed in the new release
