### ISSUE TITLE
Inconsistencies in bootPMSignature documentation

### ISSUE THREAD

**Issue by funnell** [friend1ws/pmsignature#5]
**Usage**

bootPMSignature(mutationFeatureData, Param0, bootNum = 10, BG = NULL,
  tol = 0.01, maxIter = 10000)

| Arguments | - |
| --- | --- |
| Param0 | the initial value for the parameter of memberships used for bootstraped parameter estimations |
| bootNum | the number of performing bootstrap calculations |
| BG | the background signature used for estimating Param0 |
| tol | tolerance for the estimation |
| G | the matrix of mutation feature data |
| numInit | the number of performing calculations with different initial values |

**Comment by friend1ws** [comment]
Thanks, I fixed this inconsistency in the devel branch and will be come out in the next release..

**Comment by friend1ws** [comment]
fixed in the new release
